### PR TITLE
Rerender and update libraries

### PR DESCRIPTION
**Pull request by ukaratay**

### CODE REVIEW

**Comment by ukaratay** [comment]
@synapticarbors, @aldanor  can you guys merge this pull request as well? I realized that we can update the openmp, libcxx and clangdev to 6.*.

**Comment by aldanor** [comment]
Maybe I'm a bit out of the loop here, but what's the reason for bumping these right now? 

A quick conda index search yields literally just one or two cases (e.g., `pocl` package) that have clangdev/libcxx v6 listed as their runtime requirements. Given that there's a bunch of libraries requiring v5, wouldn't this lead to needless version conflicts?

**Comment by ukaratay** [comment]
What about setting it to greater than 4.0.* instead of pinning it? That would also minimize the version conflicts.

**Comment by mariusvniekerk** [comment]
We should rather merge #10 which allows us to do a bunch of these things more globally in all of conda-forge

**Pull request closed without merging**
